// DO NOT EDIT. generated by github.com/tinywasm/orm

package app

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/form/input"
)

var _schemastateResponse = []fmt.Field{
		{Name: "jsonrpc", Type: fmt.FieldText, Widget: input.Text()},
		{Name: "id", Type: fmt.FieldRaw},
		{Name: "result", Type: fmt.FieldRaw},
	}

func (m *stateResponse) Schema() []fmt.Field { return _schemastateResponse }

func (m *stateResponse) Pointers() []any { return []any{&m.JSONRPC, &m.ID, &m.Result} }

type stateResponseList []*stateResponse

func (s *stateResponseList) Schema() []fmt.Field { return nil }
func (s *stateResponseList) Pointers() []any     { return nil }
func (s *stateResponseList) Len() int             { return len(*s) }
func (s *stateResponseList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *stateResponseList) Append() fmt.Fielder  { v := &stateResponse{}; *s = append(*s, v); return v }

func (m *stateResponse) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}
